In [2]:
import numpy as np

In [56]:
A = np.array([1, 4, 5, "8"], float)
B = np.array([4, 5, 6, 7], float)
C = np.array([[1, 2, 5, 8],[1, 2, 5, 8],[1,2,5,8]], float)
tensor_rank3 = np.array([
        [[1,2,5,8], [1,2,5,8], [1,2,5,8],],
        [[1,2,5,8], [1,2,5,8], [1,2,5,8],],
        [[1,2,5,8], [1,2,5,8], [1,2,5,8],],
        [[1,2,5,8], [1,2,5,8], [1,2,5,8],]
        ])
sli_array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)


In [30]:
print(A)
print(type(A))
print(type(A[3]))

[1. 4. 5. 8.]
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [ ]:
print(A.dtype)
print(A.shape)

float64
(4,)
(4, 3, 4)


In [48]:
print(C.shape)
print(tensor_rank3.shape)

(3, 4)
(4, 3, 4)


In [52]:
x = np.array(range(8)).reshape(4,2)

In [54]:
x.reshape(2,-1)
x.reshape(2, 2, -1)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [59]:
sli_array[:,2:]

sli_array[1,1:3]

sli_array[1:3]

array([[ 6,  7,  8,  9, 10]])